version: '2'

services:

  mariadb:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=ponty
      - MYSQL_DATABASE=wordpress

  wpfpm:
    image: wordpress:4.5.2-fpm
    links:
      - mariadb:mysql
    volumes:
      - ./ponty-connector:/var/www/html/wp-content/plugins/ponty-connector
      - ../wpbones:/var/www/html/wp-content/themes/wptheme
    environment:
      - WORDPRESS_DB_PASSWORD=ponty
    depends_on:
      - mariadb

  nginx:
    image: nginx:1.10-alpine
    volumes:
      - ./docker-wp/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - wpfpm
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - wpfpm

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mariadb:db
    ports:
      - "8088:80"
    depends_on:
      - mariadb
